esphome:
  name: haier
  platform: ESP8266
  board: d1_mini
  includes:
    - Haier.h

# Set statul led for Wemos D1 mini
status_led:
  pin: GPIO2

wifi:
  ssid: ""
  password: ""

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Haier_wifi"
    password: "Haier_wifi"

captive_portal:

# Enable web server (can be disabled)
web_server:
  port: 80

time:
  - platform: sntp
    id: sntp_time
    timezone: "Asia/ Yekaterinburg"

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0 #Important. You can't use serial port

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

climate:
  - platform: custom
    lambda: |-
      auto haier = new Haier();
      App.register_component(haier);
      return {haier};
    climates:
      - name: "Haier"